title: "Ahmad Charkhab"
tagline: "Personal blog & terminal sandbox"
description: "دنیای دیجیتال از دید کسی که عاشق تست کردن, خراب کردن و دوباره ساختن چیزهاست. اینجا تجربیات و ماجراجویی‌های فنی‌ام رو به اشتراک میذارم."
github_username: tareqdandachi
baseurl: ""
url: "https://ahmadcharkhab.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
